deploy/server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tryon.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deploy/server/tryon/urls.py
from django.urls import path
from . import views

app_name = 'tryon'

urlpatterns = [
    path('', views.TryonView.as_view(), name='home'),
    path('predict', views.TryonPredict.as_view(), name='predict'),
] 

deploy/server/tryon/models.py
from django.db import models

# Create your models here.
class Tryon(models.Model):
    pose = models.ImageField(upload_to="image")
    cloth = models.ImageField(upload_to="cloth")

    def __str__(self):
        return self.id

deploy/server/tryon/forms.py
from django import forms
from tryon.models import Tryon

class TryonForm(forms.ModelForm):
    class Meta:
        model = Tryon
        fields = ['pose', 'cloth']

deploy/server/tryon/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.template import Template
from tryon.models import Tryon
from tryon.forms import TryonForm
import os
from os import path
import sys
sys.path.append(os.path.abspath('model'))
sys.path.append(os.path.abspath('media'))
from virtuon import virtuon
from clear import clear
from pairs import pairs

# Create your views here.

class TryonView(CreateView):
    model = Tryon
    template = "index.html"
    success_url = "predict.html"


    def get(self, request):
        clear()
        form = TryonForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = TryonForm(request.POST, request.FILES or None)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)
        form.save()
        return redirect('tryon:predict')

class TryonPredict(ListView):
    template = "predict.html"

    def get(self, request):
        if path.isfile("media/output/d0.jpg") is not True:        
            pairs()
            virtuon()
        cloth = ("cloth/c0.jpg")
        pose = ("image/d0.jpg")
        output = ("output/d0.jpg")
        ctx = {"output": output, "cloth": cloth, "pose": pose}

        return render(request, self.template, ctx)

deploy/server/tryon/templates/home.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Virtuon</title>

</head>

<body>

    <h1> Welcome to the Virtual Tryon Network!! </h1>
    <p>
    <form action="" method="post" id="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'tryon:home' %}'; return false;">
    </form>
    </p>
    


</body>

</html>

deploy/server/tryon/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
 
     <!-- Site Metas -->
    <title>Virtuon</title>  
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/logo2.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
	<link rel="stylesheet" href="{% static 'css/form.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<script src="{% static 'js/modernizr.js' %}"></script> <!-- Modernizr -->

</head>
<body id="page-top" class="politics_version">

    <!-- LOADER -->
    <div id="preloader">
        <div id="main-ld">
			<div id="loader"></div>  
		</div>
    </div><!-- end loader -->
    <!-- END LOADER -->
	
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" >
			<img style="margin-left:0px;" class="img-fluid" src="{% static 'images/logo3.png' %}" alt="" />
		</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger active" >Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" >About Us</a>
            </li>
			<li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact Us</a>
            </li>
          </ul>
        </div>
      </div>
    </nav> 
	
	<section id="home" class="main-banner parallaxie" style="background: url('static/uploads/front_banner.jpg')">
		<div class="heading">
			<h1>Welcome to Virtuon</h1>			
			<h3 class="cd-headline clip is-full-width">
				<span>Virtual Try On Network</span>
				<span class="cd-words-wrapper">
					<b class="is-visible">-Wear</b>
					<b>-Look</b>
					<b>-See</b>
					<b>-Change</b>
				</span>
				<div class="btn-ber">
					<a class="get_btn hvr-bounce-to-top js-scroll-trigger" href="#portfolio">Get started</a>
					<a class="learn_btn hvr-bounce-to-top" href="#">Learn More</a>
				</div>
			</h3>
		</div>
	</section>

    <div id="about" class="section wb">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="message-box">                        
                        <h2>Welcome to Virtuon</h2>
                        <p> The objective is to transfer garments across images of people with arbitrary body pose, shape and clothing. Garment transfer is a challenging task that requires</p>
						<p>Disentangling the features of the clothing from the body pose and shape and </p>
						<p>Realistic synthesis of the garment texture on the new body.</p>

                        <a href="#" class="sim-btn hvr-bounce-to-top"><span>Contact Us</span></a>
                    </div><!-- end messagebox -->
                </div><!-- end col -->

                <div class="col-md-6">
                    <div class="right-box-pro wow fadeIn">
                        <img src="{% static 'uploads/tryon.jpg' %}" alt="" class="img-fluid img-rounded">
                    </div><!-- end media -->
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->
	
	<div id="portfolio" class="section lb">
		<div class="container">
			<div class="section-title text-center">
                <h3>Let's Try -Virtual Tron</h3>
                <p>Wondering how would you will look,we have solution to our problem.</p>
            </div><!-- end title -->
			<div style="text-align:center;" class="login-wrap">
				<div class="login-html">
					<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Upload your input Images</label>
					<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"></label>
					<div class="login-form">
						<div class="sign-in-htm">
						<form action="" method="post" id="upload_form" enctype="multipart/form-data">
							{% csrf_token %}
							{% for field in form %}
								<div class="group">
									<label for="user" class="label">{{ field.label }} Image</label>
									{{ field }}
								</div>
							{% endfor %}

							<div class="group">
								<input type="submit" class="button" value="Perdict">
							</div>
						</form>

							<div class="hr"> </div>
							<div class="foot-lnk">
								<a style="font-style:bold;color:aliceblue" href="#">By Team Virtuon</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
			
    <div id="contact" class="section db">
        <div class="container">
            <div class="section-title text-center">
                <h3>Contact</h3>
<!--                 <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p> -->
            </div><!-- end title -->

            <div class="row">
                <div class="col-md-12">
                    <div class="contact_form">
                        <div id="message"></div>
                        <form id="contactForm" name="sentMessage" novalidate="novalidate">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input class="form-control" id="name" type="text" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name.">
										<p class="help-block text-danger"></p>
									</div>
									<div class="form-group">
										<input class="form-control" id="email" type="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email address.">
										<p class="help-block text-danger"></p>
									</div>
									<div class="form-group">
										<input class="form-control" id="phone" type="tel" placeholder="Your Phone" required="required" data-validation-required-message="Please enter your phone number.">
										<p class="help-block text-danger"></p>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<textarea class="form-control" id="message" placeholder="Your Message" required="required" data-validation-required-message="Please enter a message."></textarea>
										<p class="help-block text-danger"></p>
									</div>
								</div>
								<div class="clearfix"></div>
								<div class="col-lg-12 text-center">
									<div id="success"></div>
									<button id="sendMessageButton" class="sim-btn hvr-bounce-to-top" type="submit">Send Message</button>
								</div>
							</div>
						</form>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end section -->

    <div class="copyrights">
        <div class="container">
            <div class="footer-distributed">
				<a href="#"><img src="{% static 'images/logo3.png' %}" alt="" /></a>
                <div class="footer-center">
                    <p class="footer-links">
                        <a href="#">Home</a>
                        <a href="#">About</a>
                        <a href="#">Faq</a>
                        <a href="#">Contact</a>
                    </p>
                    <p class="footer-company-name">All Rights Reserved. &copy; 2021 <a href="#">VIRTUON</a> Design By : 
					<a href="https://html.design/">Virtuon design</a></p>
                </div>
            </div>
        </div><!-- end container -->
    </div><!-- end copyrights -->

    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'js/all.js' %}"></script>
	<!-- Camera Slider -->
	<script src="{% static 'js/parallaxie.js' %}"></script>
	<script src="{% static 'js/headline.js' %}"></script>
	<!-- Contact form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/jquery.vide.js' %}"></script>

</body>
</html>

deploy/server/tryon/templates/predict.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<style>
*{
  box-sizing: border-box;
}

html {
    background-color: #eefbf8;
   /* background-image: radial-gradient(circle, hsla(0,0%,100%,.1), hsla(0,0%,0%,.75)),
                      linear-gradient(left, transparent 50%, hsla(0,0%,0%,.01) 50%);*/
                           
  
    
}
.bac{
    background-image: url("static/uploads/banner_2_2-D.jpg");
    min-width: min-content;
    /* Full height */
    max-width: 1550px;
    height: 400px;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  margin-left:auto;
  margin-right:auto;
}
.column {
  float: left;
  width: 33.33%;
  padding: 50px;
  margin-left:auto;
  margin-right:auto;
}
.slider{
    background-color: #fff;
    box-shadow: inset 0 0 2px hsla(0,0%,0%,.2),
                0 3px 1px hsla(0,0%,100%,.75),
                0 -1px 1px 2px 
}
img{
  max-width: 100%;
  height: auto;
  border: 1px solid;
  padding: 10px;
  box-shadow: 0 20px 20px -6px black;
}
/* Clearfix (clear floats) */
.row::after {

  content: "";
  clear: both;
  display: table;
}
</style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>

    <link rel="shortcut icon" href="{% static 'images/logo2.png' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">
</head>
<body>
<div  class="bac">
    </div>
</div>
<div style="margin: 30px 4px ; background-image: radial-gradient(circle, hsla(0,0%,100%,.1), hsla(0,0%,0%,.75)),
linear-gradient(left, transparent 50%, hsla(0,0%,0%,.01) 50%);">

<div class="row">
  <div class="column">
  <center>
    <h2>Pose Image</h2>
    <img style="height:256px;width:192px;margin:20px auto" class="slider" src="{{MEDIA_URL}}{{pose}}" alt="Snow" style="width:100%">
  </center>
  </div>
  
  <div class="column">
  <center>
    <h2>Cloth Image</h2>  
    <img style="height:256px;width:192px;margin:20px auto" class="slider" src="{{MEDIA_URL}}{{cloth}}" alt="Forest" style="width:100%">
  </center>
  </div>

  <div class="column">
  <center>
    <h2>Predicted Image</h2>
    <img style="height:256px;width:192px;margin:20px auto"class="slider" src="{{MEDIA_URL}}{{output}}" alt="Mountains" style="width:100%">
  </center>
  </div>
</div>
</div>
</body>
</html>

deploy/server/tryon/templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        img {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 5px;
            width: 150px;
          }
          
          
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Virtuon</title>
</head>
<body>
    <div style="margin:0px">
<div style="background-color:rgb(116, 52, 235);height:70px;">
    <h1 style="text-align:center;margin-top:50px;font-size:30px" >Let, see your virtual tryon output</h1>
</div>
<!-- <h1 style="text-align:center;background-color:rgb(52, 211, 235) ;color:black;"> Here's your result! </h1> -->
<span>
<div style="width:100%; text-align:left">
<img class="img" style="border-style:solid;border-color: rgb(52, 180, 235);width:192px; height:256px;" src="{{MEDIA_URL}}{{pose}}">
</div> 
<div style="width:100%; text-align:center">
<img class="img" style="border-style:solid;border-color: rgb(52, 180, 235);width:192px; height:256px;" src="{{MEDIA_URL}}{{output}}">
</div> 
<div style="width:100%; text-align:right">
<img class="img" style="border-style:solid;border-color: rgb(52, 180, 235);width:192px; height:256px;" src="{{MEDIA_URL}}{{cloth}}">
</div> 
</span>
</div>
</body>
</html>